[package]
build="build.rs"
name = "word2vec"
version = "0.1.0"
edition = "2021"
authors = ["mklf <golifang1234@gmail.com>", "lambdaofgod <bartczukkuba@gmail.com>"]

[lib]
name = "word2vec"
path ="src/lib.rs"
[[bin]]
name = "word2vec"
path = "src/main.rs"
doc = false

[build-dependencies]
gcc = "0.3"

[dependencies]
rand = "0.4"
clap = "2.33.3"
time = "*"
libc= "*"
parquet = "11.1.0"
